In [1]:
import pandas as pd
import numpy as np


# инструменты для построения модели:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression # инструмент для создания и обучения модели
from sklearn.ensemble import RandomForestRegressor # инструмент для создания и обучения модели
from sklearn import metrics # инструменты для оценки точности модели

import matplotlib as plt

import pickle

from sklearn.utils import shuffle

RANDOM_SEED = 42

In [2]:
df = pd.read_csv('data/dataset_prepaired.csv')
df.head()

,Linera density,Density yarn,Strength Gpa,Module Gpa,lengthening,Mass size,breaking the loop,Surface density of the fabric,Prepreg surface density,Resin content,viscosity,Gelation time,Resin Tg,technology,Thickness of the monolayer,density,Strength_plastik,Module_plastik,LSS,Plastik_Tg
0,188.0,1.758,4.59,253.0,1.814229,1.0,24.3,196.0,319.4,38.63,23.672,19.0,150.2,0,0.209,1.536,879.0,70.1,77.2,164.0
1,189.0,1.758,4.48,260.0,1.723077,1.1,24.3,196.0,319.4,38.63,23.672,19.0,150.2,0,0.209,1.536,879.0,70.1,77.2,164.0
2,188.0,1.759,4.28,257.0,1.665370,1.0,24.3,196.0,319.4,38.63,23.672,19.0,150.2,0,0.209,1.536,879.0,70.1,77.2,164.0
3,187.0,1.758,4.77,256.0,1.863281,1.0,24.3,196.0,319.4,38.63,23.672,19.0,150.2,0,0.209,1.536,879.0,70.1,77.2,164.0
4,190.0,1.757,4.56,255.0,1.788235,0.9,24.3,196.0,319.4,38.63,23.672,19.0,150.2,0,0.209,1.536,879.0,70.1,77.2,164.0

In [3]:
df = df[df['technology'] == 1]
df = df.drop('technology', axis=1)

df = df.rename(columns={'Thickness of the monolayer' : 'Thickness_monolayer',
                        'Module_plastik ' : 'Module_plastik'})

In [4]:
df.head()

,Linera density,Density yarn,Strength Gpa,Module Gpa,lengthening,Mass size,breaking the loop,Surface density of the fabric,Prepreg surface density,Resin content,viscosity,Gelation time,Resin Tg,Thickness_monolayer,density,Strength_plastik,Module_plastik,LSS,Plastik_Tg
426,188.0,1.752,4.29,254.0,1.688976,1.1,26.2,197.5,321.37,38.97,25.2,19.0,152.0,0.209,1.555,922.0,71.7,78.9,156.0
427,184.0,1.751,4.30,255.0,1.686275,1.2,24.7,197.5,321.37,38.97,25.2,19.0,152.0,0.209,1.555,922.0,71.7,78.9,156.0
428,179.0,1.750,4.62,268.0,1.723881,1.2,26.3,197.5,321.37,38.97,25.2,19.0,152.0,0.209,1.555,922.0,71.7,78.9,156.0
429,189.0,1.749,4.37,254.0,1.720472,1.1,25.6,197.5,321.37,38.97,25.2,19.0,152.0,0.209,1.555,922.0,71.7,78.9,156.0
430,189.0,1.749,4.26,255.0,1.670588,1.0,24.8,197.5,321.37,38.97,25.2,19.0,152.0,0.209,1.555,922.0,71.7,78.9,156.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6913 entries, 426 to 10710
Data columns (total 19 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Linera density                 6913 non-null   float64
 1   Density yarn                   6913 non-null   float64
 2   Strength Gpa                   6913 non-null   float64
 3   Module Gpa                     6913 non-null   float64
 4   lengthening                    6913 non-null   float64
 5   Mass size                      6913 non-null   float64
 6   breaking the loop              6913 non-null   float64
 7   Surface density of the fabric  6913 non-null   float64
 8   Prepreg surface density        6913 non-null   float64
 9   Resin content                  6913 non-null   float64
 10  viscosity                      6913 non-null   float64
 11  Gelation time                  6913 non-null   float64
 12  Resin Tg                       6913 non-null   float64
 13  Thickness_monolayer            6913 non-null   float64
 14  density                        6913 non-null   float64
 15  Strength_plastik               6913 non-null   float64
 16  Module_plastik                 6913 non-null   float64
 17  LSS                            6913 non-null   float64
 18  Plastik_Tg                     6913 non-null   float64
dtypes: float64(19)
memory usage: 1.1 MB

In [6]:
df_strenght = df.drop(['Surface density of the fabric', 'Prepreg surface density', 'viscosity', 
                       'Gelation time', 'Resin Tg'], axis=1)

In [17]:
train_data_strength = df_strenght.drop(['Thickness_monolayer', 'Module_plastik',
       'LSS', 'Plastik_Tg', 'density'], axis=1)

X = np.array(train_data_strength.drop(['Strength_plastik'], axis=1))
y = np.array(train_data_strength.Strength_plastik.values)

In [18]:
# воспользуемся специальной функцие train_test_split для разделения тестовых данных
# выделим 20% данных на валидацию (параметр test_size)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_SEED)

In [27]:
# НАСТРОЙКИ 
model_rf_strength = RandomForestRegressor(
    n_estimators=5000,
    max_features=4,
    min_samples_leaf=5,
    max_depth=10,
    verbose=1, 
    n_jobs=-1, 
    random_state=RANDOM_SEED)

# обучаем модель на тестовом наборе данных
model_rf_strength.fit(X_train, y_train)

# предсказанные значения записываем в переменную y_pred
y_pred = model_rf_strength.predict(X_test)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  26 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done 176 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 426 tasks      | elapsed:    0.3s
[Parallel(n_jobs=-1)]: Done 776 tasks      | elapsed:    0.5s
[Parallel(n_jobs=-1)]: Done 1226 tasks      | elapsed:    0.8s
[Parallel(n_jobs=-1)]: Done 1776 tasks      | elapsed:    1.1s
[Parallel(n_jobs=-1)]: Done 2426 tasks      | elapsed:    1.5s
[Parallel(n_jobs=-1)]: Done 3176 tasks      | elapsed:    2.0s
[Parallel(n_jobs=-1)]: Done 4026 tasks      | elapsed:    2.5s
[Parallel(n_jobs=-1)]: Done 4976 tasks      | elapsed:    3.1s
[Parallel(n_jobs=-1)]: Done 5000 out of 5000 | elapsed:    3.1s finished
[Parallel(n_jobs=12)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done  26 tasks      | elapsed:    0.0s
[Parallel(n_jobs=12)]: Done 176 tasks      | elapsed:    0.0s
[Parallel(n_jobs=12)]: Done 426 tasks      | elapsed:    0.0s
[Parallel(n_jobs=12)]: Done 776 tasks      | elapsed:    0.1s
[Parallel(n_jobs=12)]: Done 1226 tasks      | elapsed:    0.1s
[Parallel(n_jobs=12)]: Done 1776 tasks      | elapsed:    0.1s
[Parallel(n_jobs=12)]: Done 2426 tasks      | elapsed:    0.2s
[Parallel(n_jobs=12)]: Done 3176 tasks      | elapsed:    0.2s
[Parallel(n_jobs=12)]: Done 4026 tasks      | elapsed:    0.3s
[Parallel(n_jobs=12)]: Done 4976 tasks      | elapsed:    0.3s
[Parallel(n_jobs=12)]: Done 5000 out of 5000 | elapsed:    0.3s finished

In [25]:
def mean_absolute_percentage_error(y_tr, y_pr):
    """Получение средней абсолютной ошибки"""
    y_tr, y_pr = np.array(y_tr), np.array(y_pr)
    return np.mean(np.abs((y_tr - y_pr) / y_tr)) * 100

# сравниваем предсказанные значения (y_pred) с реальными (y_test), 
# метрика mean squared error, MSE показывает среднеквадратичное отклонение:

def mean_squared_error(y_tr, y_pr):
    """Получение средней абсолютной ошибки"""
    y_tr, y_pr = np.array(y_tr), np.array(y_pr)
    return np.mean(np.abs((y_tr - y_pr)**2))

In [28]:
print('model_rf_strength MSE:', round(mean_squared_error(y_test, y_pred), 3))

print('model_rf_strength MAPE:', round(mean_absolute_percentage_error(y_test, y_pred), 3))

model_rf_strength MSE: 34.402
model_rf_strength MAPE: 0.16

In [14]:
df_strenght.head()

,Linera density,Density yarn,Strength Gpa,Module Gpa,lengthening,Mass size,breaking the loop,Resin content,Thickness_monolayer,density,Strength_plastik,Module_plastik,LSS,Plastik_Tg
426,188.0,1.752,4.29,254.0,1.688976,1.1,26.2,38.97,0.209,1.555,922.0,71.7,78.9,156.0
427,184.0,1.751,4.30,255.0,1.686275,1.2,24.7,38.97,0.209,1.555,922.0,71.7,78.9,156.0
428,179.0,1.750,4.62,268.0,1.723881,1.2,26.3,38.97,0.209,1.555,922.0,71.7,78.9,156.0
429,189.0,1.749,4.37,254.0,1.720472,1.1,25.6,38.97,0.209,1.555,922.0,71.7,78.9,156.0
430,189.0,1.749,4.26,255.0,1.670588,1.0,24.8,38.97,0.209,1.555,922.0,71.7,78.9,156.0

In [22]:
x1 = np.array([[185.62, 1.769, 4.56, 261, 1.75, 1.07, 26.8, 38.57]])
x2 = np.array([[185.62, 1.769, 4.56, 261, 1.75, 1.07, 26.8, 39.43]])

In [29]:
print('Случайный лес регрессия. Прочность:', model_rf_strength.predict(x1))

[Parallel(n_jobs=12)]: Using backend ThreadingBackend with 12 concurrent workers.
[Parallel(n_jobs=12)]: Done  26 tasks      | elapsed:    0.0s
[Parallel(n_jobs=12)]: Done 176 tasks      | elapsed:    0.0s
[Parallel(n_jobs=12)]: Done 426 tasks      | elapsed:    0.0s
[Parallel(n_jobs=12)]: Done 776 tasks      | elapsed:    0.0s
[Parallel(n_jobs=12)]: Done 1226 tasks      | elapsed:    0.1s
[Parallel(n_jobs=12)]: Done 1776 tasks      | elapsed:    0.1s
[Parallel(n_jobs=12)]: Done 2426 tasks      | elapsed:    0.2s
[Parallel(n_jobs=12)]: Done 3176 tasks      | elapsed:    0.3s
[Parallel(n_jobs=12)]: Done 4026 tasks      | elapsed:    0.4s

Случайный лес регрессия. Прочность: [905.89358833]

[Parallel(n_jobs=12)]: Done 4976 tasks      | elapsed:    0.6s
[Parallel(n_jobs=12)]: Done 5000 out of 5000 | elapsed:    0.6s finished