In [111]:
import pandas as pd
import numpy as np
from openpyxl import load_workbook

In [112]:
df_144 = pd.read_excel('data/81-144.xlsx')

In [113]:
df_144

,Linera density,SA linear,Density yarn,Strength Gpa,Module Gpa,lengthening,Mass size,breaking the loop,Surface density of the fabric,Prepreg surface density,...,viscosity,Gelation time,Resin Tg,technology,Thickness of the monolayer,density,Strength_plastik,Module_plastik,LSS,Plastik_Tg
0,188,-1.052632,1.758,4.59,253,1.814229,1,-,196.0,319.4,...,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
1,189,-0.526316,1.758,4.48,260,1.723077,1.1,-,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,188,-1.052632,1.759,4.28,257,1.665370,1,-,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,187,-1.578947,1.758,4.77,256,1.863281,1,-,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,190,0.000000,1.757,4.56,255,1.788235,0.9,-,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,183,-3.684211,1.768,4.54,261,1.739464,-,-,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
422,184,-3.157895,1.770,4.43,262,1.690840,-,-,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
423,183,-3.684211,1.769,4.32,265,1.630189,-,-,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
424,187,-1.578947,1.769,4.32,261,1.655172,-,-,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
425,190,0.000000,1.768,4.27,253,1.687747,-,-,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [114]:
df_144 = df_144.drop('SA linear', axis=1)

In [115]:
df_144 = df_144.replace('-', np.nan, regex=True)

/tmp/ipykernel_9851/2346722493.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_144 = df_144.replace('-', np.nan, regex=True)

In [116]:
df_144

,Linera density,Density yarn,Strength Gpa,Module Gpa,lengthening,Mass size,breaking the loop,Surface density of the fabric,Prepreg surface density,Resin content,viscosity,Gelation time,Resin Tg,technology,Thickness of the monolayer,density,Strength_plastik,Module_plastik,LSS,Plastik_Tg
0,188,1.758,4.59,253,1.814229,1.0,NaN,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
1,189,1.758,4.48,260,1.723077,1.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,188,1.759,4.28,257,1.665370,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,187,1.758,4.77,256,1.863281,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,190,1.757,4.56,255,1.788235,0.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,183,1.768,4.54,261,1.739464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
422,184,1.770,4.43,262,1.690840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
423,183,1.769,4.32,265,1.630189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
424,187,1.769,4.32,261,1.655172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
425,190,1.768,4.27,253,1.687747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [117]:
df_144.isnull().sum()

Linera density                     0
Density yarn                       0
Strength Gpa                       0
Module Gpa                         0
lengthening                        0
Mass size                        395
breaking the loop                349
Surface density of the fabric    425
Prepreg surface density          425
Resin content                    425
viscosity                        425
Gelation time                    425
Resin Tg                         425
technology                       425
Thickness of the monolayer       425
density                          425
Strength_plastik                 425
Module_plastik                   425
LSS                              425
Plastik_Tg                       425
dtype: int64

In [118]:
df_144['technology'] = np.where(df_144['technology'].isnull(), 'v', 'v')
df_144

,Linera density,Density yarn,Strength Gpa,Module Gpa,lengthening,Mass size,breaking the loop,Surface density of the fabric,Prepreg surface density,Resin content,viscosity,Gelation time,Resin Tg,technology,Thickness of the monolayer,density,Strength_plastik,Module_plastik,LSS,Plastik_Tg
0,188,1.758,4.59,253,1.814229,1.0,NaN,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
1,189,1.758,4.48,260,1.723077,1.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,v,NaN,NaN,NaN,NaN,NaN,NaN
2,188,1.759,4.28,257,1.665370,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,v,NaN,NaN,NaN,NaN,NaN,NaN
3,187,1.758,4.77,256,1.863281,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,v,NaN,NaN,NaN,NaN,NaN,NaN
4,190,1.757,4.56,255,1.788235,0.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,v,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,183,1.768,4.54,261,1.739464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,v,NaN,NaN,NaN,NaN,NaN,NaN
422,184,1.770,4.43,262,1.690840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,v,NaN,NaN,NaN,NaN,NaN,NaN
423,183,1.769,4.32,265,1.630189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,v,NaN,NaN,NaN,NaN,NaN,NaN
424,187,1.769,4.32,261,1.655172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,v,NaN,NaN,NaN,NaN,NaN,NaN
425,190,1.768,4.27,253,1.687747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,v,NaN,NaN,NaN,NaN,NaN,NaN

In [119]:
def replace_nan(df):
    
    df['Mass size'] = df['Mass size'].fillna(df['Mass size'].mean())
    df['breaking the loop'] = df['breaking the loop'].fillna(df['breaking the loop'].median())
    df['Surface density of the fabric'] = df['Surface density of the fabric'].fillna(df['Surface density of the fabric'].mean())
    df['Prepreg surface density'] = df['Prepreg surface density'].fillna(df['Prepreg surface density'].mean())
    df['Resin content'] = df['Resin content'].fillna(df['Resin content'].mean())
    df['viscosity'] = df['viscosity'].fillna(df['viscosity'].mean())
    df['Gelation time'] = df['Gelation time'].fillna(df['Gelation time'].mean())
    df['Resin Tg'] = df['Resin Tg'].fillna(df['Resin Tg'].mean())
    df['Thickness of the monolayer'] = df['Thickness of the monolayer'].fillna(df['Thickness of the monolayer'].mean())
    df['density'] = df['density'].fillna(df['density'].mean())
    df['Strength_plastik'] = df['Strength_plastik'].fillna(df['Strength_plastik'].median())
    df['Module_plastik '] = df['Module_plastik '].fillna(df['Module_plastik '].median())
    df['LSS'] = df['LSS'].fillna(df['LSS'].mean())
    df['Plastik_Tg'] = df['Plastik_Tg'].fillna(df['Plastik_Tg'].mean())
    
    return df

In [120]:
replace_nan(df_144)
df_144

,Linera density,Density yarn,Strength Gpa,Module Gpa,lengthening,Mass size,breaking the loop,Surface density of the fabric,Prepreg surface density,Resin content,viscosity,Gelation time,Resin Tg,technology,Thickness of the monolayer,density,Strength_plastik,Module_plastik,LSS,Plastik_Tg
0,188,1.758,4.59,253,1.814229,1.000000,24.3,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
1,189,1.758,4.48,260,1.723077,1.100000,24.3,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
2,188,1.759,4.28,257,1.665370,1.000000,24.3,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
3,187,1.758,4.77,256,1.863281,1.000000,24.3,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
4,190,1.757,4.56,255,1.788235,0.900000,24.3,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421,183,1.768,4.54,261,1.739464,1.070968,24.3,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
422,184,1.770,4.43,262,1.690840,1.070968,24.3,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
423,183,1.769,4.32,265,1.630189,1.070968,24.3,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
424,187,1.769,4.32,261,1.655172,1.070968,24.3,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0
425,190,1.768,4.27,253,1.687747,1.070968,24.3,196.0,319.4,38.63,23.672,19.0,150.2,v,0.209,1.536,879.0,70.1,77.2,164.0